
import java.awt.event.KeyEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fahad
 */
public class NewJFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        breakfastMenu = new javax.swing.JPanel();
        fryeggcheck = new javax.swing.JCheckBox();
        parathacheck = new javax.swing.JCheckBox();
        naancheck = new javax.swing.JCheckBox();
        halwapuricheck = new javax.swing.JCheckBox();
        ommlettecheck = new javax.swing.JCheckBox();
        halwaplatecheck = new javax.swing.JCheckBox();
        niharicheck = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        fryeggqty = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        parathaqty = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        ommletteqty = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        halwaplateqty = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        naanqty = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        halwapuriqty = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        nihariqty = new javax.swing.JTextArea();
        jTextField11 = new javax.swing.JTextField();
        jScrollPane15 = new javax.swing.JScrollPane();
        channyhalfqty = new javax.swing.JTextArea();
        channyhalfcheck = new javax.swing.JCheckBox();
        jScrollPane16 = new javax.swing.JScrollPane();
        channyfullqty = new javax.swing.JTextArea();
        channyfullcheck = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        breakfastMenu.setBackground(new java.awt.Color(102, 8, 219));
        breakfastMenu.setToolTipText("");
        breakfastMenu.setPreferredSize(new java.awt.Dimension(400, 900));
        breakfastMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fryeggcheck.setBackground(new java.awt.Color(102, 8, 219));
        fryeggcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fryeggcheckActionPerformed(evt);
            }
        });
        breakfastMenu.add(fryeggcheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 30));

        parathacheck.setBackground(new java.awt.Color(102, 8, 219));
        parathacheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parathacheckActionPerformed(evt);
            }
        });
        breakfastMenu.add(parathacheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, 30));

        naancheck.setBackground(new java.awt.Color(102, 8, 219));
        naancheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naancheckActionPerformed(evt);
            }
        });
        breakfastMenu.add(naancheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        halwapuricheck.setBackground(new java.awt.Color(102, 8, 219));
        halwapuricheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                halwapuricheckActionPerformed(evt);
            }
        });
        breakfastMenu.add(halwapuricheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, 30));

        ommlettecheck.setBackground(new java.awt.Color(102, 8, 219));
        ommlettecheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ommlettecheckActionPerformed(evt);
            }
        });
        breakfastMenu.add(ommlettecheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, 30));

        halwaplatecheck.setBackground(new java.awt.Color(102, 8, 219));
        halwaplatecheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        halwaplatecheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                halwaplatecheckActionPerformed(evt);
            }
        });
        breakfastMenu.add(halwaplatecheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, -1, 20));

        niharicheck.setBackground(new java.awt.Color(102, 8, 219));
        niharicheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                niharicheckActionPerformed(evt);
            }
        });
        breakfastMenu.add(niharicheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, -1, 20));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        fryeggqty.setColumns(20);
        fryeggqty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fryeggqty.setRows(5);
        fryeggqty.setText("0");
        fryeggqty.setEnabled(false);
        fryeggqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fryeggqtyKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(fryeggqty);

        breakfastMenu.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 93, 31));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        parathaqty.setColumns(20);
        parathaqty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        parathaqty.setRows(5);
        parathaqty.setText("0");
        parathaqty.setEnabled(false);
        parathaqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                parathaqtyKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(parathaqty);

        breakfastMenu.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 93, 31));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        ommletteqty.setColumns(20);
        ommletteqty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ommletteqty.setRows(5);
        ommletteqty.setText("0");
        ommletteqty.setEnabled(false);
        ommletteqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ommletteqtyKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(ommletteqty);

        breakfastMenu.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 93, 31));

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        halwaplateqty.setColumns(20);
        halwaplateqty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        halwaplateqty.setRows(5);
        halwaplateqty.setText("0");
        halwaplateqty.setEnabled(false);
        halwaplateqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                halwaplateqtyKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(halwaplateqty);

        breakfastMenu.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 650, 93, 31));

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        naanqty.setColumns(20);
        naanqty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        naanqty.setRows(5);
        naanqty.setText("0");
        naanqty.setEnabled(false);
        naanqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                naanqtyKeyTyped(evt);
            }
        });
        jScrollPane5.setViewportView(naanqty);

        breakfastMenu.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 93, 31));

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        halwapuriqty.setColumns(20);
        halwapuriqty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        halwapuriqty.setRows(5);
        halwapuriqty.setText("0");
        halwapuriqty.setEnabled(false);
        halwapuriqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                halwapuriqtyKeyTyped(evt);
            }
        });
        jScrollPane6.setViewportView(halwapuriqty);

        breakfastMenu.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 93, 31));

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        nihariqty.setColumns(20);
        nihariqty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nihariqty.setRows(5);
        nihariqty.setText("0");
        nihariqty.setEnabled(false);
        nihariqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nihariqtyKeyTyped(evt);
            }
        });
        jScrollPane7.setViewportView(nihariqty);

        breakfastMenu.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 590, 93, 31));

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(255, 255, 255));
        jTextField11.setFont(new java.awt.Font("Bahamas Bold", 0, 36)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("MENU LIST");
        jTextField11.setBorder(null);
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        breakfastMenu.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 38, 274, 52));

        jScrollPane15.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane15.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        channyhalfqty.setColumns(20);
        channyhalfqty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        channyhalfqty.setRows(5);
        channyhalfqty.setText("0");
        channyhalfqty.setEnabled(false);
        channyhalfqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                channyhalfqtyKeyTyped(evt);
            }
        });
        jScrollPane15.setViewportView(channyhalfqty);

        breakfastMenu.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 93, 31));

        channyhalfcheck.setBackground(new java.awt.Color(102, 8, 219));
        channyhalfcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channyhalfcheckActionPerformed(evt);
            }
        });
        breakfastMenu.add(channyhalfcheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, -1));

        jScrollPane16.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane16.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        channyfullqty.setColumns(20);
        channyfullqty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        channyfullqty.setRows(5);
        channyfullqty.setText("0");
        channyfullqty.setEnabled(false);
        channyfullqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                channyfullqtyKeyTyped(evt);
            }
        });
        jScrollPane16.setViewportView(channyfullqty);

        breakfastMenu.add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 93, 31));

        channyfullcheck.setBackground(new java.awt.Color(102, 8, 219));
        channyfullcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channyfullcheckActionPerformed(evt);
            }
        });
        breakfastMenu.add(channyfullcheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 21)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("HALWA PLATE");
        breakfastMenu.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 630, 170, 60));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("OMMLETTE");
        breakfastMenu.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 140, 30));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PARATHA");
        breakfastMenu.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 140, 30));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("NAAN");
        breakfastMenu.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 80, 40));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("HALWA PURI");
        breakfastMenu.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 160, 70));

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("CHANNY(full)");
        breakfastMenu.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 160, 40));

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("CHANNY(half)");
        breakfastMenu.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 160, 40));

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("NIHARI");
        breakfastMenu.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 90, 40));

        jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("FRY EGG");
        breakfastMenu.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 110, 30));

        Reset.setText("reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        breakfastMenu.add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 730, -1, -1));

        getContentPane().add(breakfastMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 420, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fryeggcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fryeggcheckActionPerformed
        // TODO add your handling code here:
        if (fryeggcheck.isSelected())
        {
            fryeggqty.setEnabled(true);
            fryeggqty.requestFocus();
            fryeggqty.setText("");
        }
        
    }//GEN-LAST:event_fryeggcheckActionPerformed

    private void naancheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naancheckActionPerformed
        // TODO add your handling code here:
        if (naancheck.isSelected())
        {
            naanqty.setEnabled(true);
            naanqty.requestFocus();
            naanqty.setText("");
        }
       
    }//GEN-LAST:event_naancheckActionPerformed

    private void halwapuricheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_halwapuricheckActionPerformed
        // TODO add your handling code here:
         if (halwapuricheck.isSelected())
        {
            halwapuriqty.setEnabled(true);
            halwapuriqty.requestFocus();
            halwapuriqty.setText("");
        }
        
    }//GEN-LAST:event_halwapuricheckActionPerformed

    private void ommlettecheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ommlettecheckActionPerformed
        // TODO add your handling code here:
        if (ommlettecheck.isSelected())
        {
            ommletteqty.setEnabled(true);
            ommletteqty.requestFocus();
            ommletteqty.setText("");
        }
        
    }//GEN-LAST:event_ommlettecheckActionPerformed

    private void halwaplatecheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_halwaplatecheckActionPerformed
        // TODO add your handling code here:
        if (halwaplatecheck.isSelected())
        {
            halwaplateqty.setEnabled(true);
            halwaplateqty.requestFocus();
            halwaplateqty.setText("");
        }
       
    }//GEN-LAST:event_halwaplatecheckActionPerformed

    private void niharicheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_niharicheckActionPerformed
        // TODO add your handling code here:
         if (niharicheck.isSelected())
        {
            nihariqty.setEnabled(true);
            nihariqty.requestFocus();
            nihariqty.setText("");
        }
       
    }//GEN-LAST:event_niharicheckActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void channyhalfcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channyhalfcheckActionPerformed
        // TODO add your handling code here:
        if (channyhalfcheck.isSelected())
        {
            channyhalfqty.setEnabled(true);
            channyhalfqty.requestFocus();
            channyhalfqty.setText("");
        }
        
    }//GEN-LAST:event_channyhalfcheckActionPerformed

    private void channyfullcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channyfullcheckActionPerformed
        // TODO add your handling code here:
        if (channyfullcheck.isSelected())
        {
            channyfullqty.setEnabled(true);
            channyfullqty.requestFocus();
            channyfullqty.setText("");
        }
        
    }//GEN-LAST:event_channyfullcheckActionPerformed

    private void fryeggqtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fryeggqtyKeyTyped
        // TODO add your handling code here:
        char numberVal = evt.getKeyChar();
        if(!(Character.isDigit(numberVal))
            ||(numberVal ==KeyEvent.VK_BACK_SPACE)
            ||(numberVal ==KeyEvent.VK_DELETE))
        evt.consume();
        
        
        
    }//GEN-LAST:event_fryeggqtyKeyTyped

    private void ommletteqtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ommletteqtyKeyTyped
        // TODO add your handling code here:
                char numberVal = evt.getKeyChar();
        if(!(Character.isDigit(numberVal))
            ||(numberVal ==KeyEvent.VK_BACK_SPACE)
            ||(numberVal ==KeyEvent.VK_DELETE))
        evt.consume();
        
        
    }//GEN-LAST:event_ommletteqtyKeyTyped

    private void parathaqtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_parathaqtyKeyTyped
        // TODO add your handling code here:
                char numberVal = evt.getKeyChar();
        if(!(Character.isDigit(numberVal))
            ||(numberVal ==KeyEvent.VK_BACK_SPACE)
            ||(numberVal ==KeyEvent.VK_DELETE))
        evt.consume();
        
        
    }//GEN-LAST:event_parathaqtyKeyTyped

    private void naanqtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_naanqtyKeyTyped
        // TODO add your handling code here:
                char numberVal = evt.getKeyChar();
        if(!(Character.isDigit(numberVal))
            ||(numberVal ==KeyEvent.VK_BACK_SPACE)
            ||(numberVal ==KeyEvent.VK_DELETE))
        evt.consume();
        
        
    }//GEN-LAST:event_naanqtyKeyTyped

    private void halwapuriqtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_halwapuriqtyKeyTyped
        // TODO add your handling code here:
                char numberVal = evt.getKeyChar();
        if(!(Character.isDigit(numberVal))
            ||(numberVal ==KeyEvent.VK_BACK_SPACE)
            ||(numberVal ==KeyEvent.VK_DELETE))
        evt.consume();
        
        
    }//GEN-LAST:event_halwapuriqtyKeyTyped

    private void channyfullqtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_channyfullqtyKeyTyped
        // TODO add your handling code here:
                char numberVal = evt.getKeyChar();
        if(!(Character.isDigit(numberVal))
            ||(numberVal ==KeyEvent.VK_BACK_SPACE)
            ||(numberVal ==KeyEvent.VK_DELETE))
        evt.consume();
        
        
    }//GEN-LAST:event_channyfullqtyKeyTyped

    private void channyhalfqtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_channyhalfqtyKeyTyped
        // TODO add your handling code here:
                char numberVal = evt.getKeyChar();
        if(!(Character.isDigit(numberVal))
            ||(numberVal ==KeyEvent.VK_BACK_SPACE)
            ||(numberVal ==KeyEvent.VK_DELETE))
        evt.consume();
        
        
    }//GEN-LAST:event_channyhalfqtyKeyTyped

    private void nihariqtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nihariqtyKeyTyped
        // TODO add your handling code here:
                char numberVal = evt.getKeyChar();
        if(!(Character.isDigit(numberVal))
            ||(numberVal ==KeyEvent.VK_BACK_SPACE)
            ||(numberVal ==KeyEvent.VK_DELETE))
        evt.consume();
        
        
    }//GEN-LAST:event_nihariqtyKeyTyped

    private void halwaplateqtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_halwaplateqtyKeyTyped
        // TODO add your handling code here:
                char numberVal = evt.getKeyChar();
        if(!(Character.isDigit(numberVal))
            ||(numberVal ==KeyEvent.VK_BACK_SPACE)
            ||(numberVal ==KeyEvent.VK_DELETE))
        evt.consume();
        
        
    }//GEN-LAST:event_halwaplateqtyKeyTyped

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        fryeggqty.setText(null);
        ommletteqty.setText(null);
        parathaqty.setText(null);
        naanqty.setText(null);
        halwapuriqty.setText(null);
        channyfullqty.setText(null);
        channyhalfqty.setText(null);
        nihariqty.setText(null);
        halwaplateqty.setText(null);
      
        //********************************
        fryeggcheck.setSelected(false);
        ommlettecheck.setSelected(false);
        parathacheck.setSelected(false);
        naancheck.setSelected(false);
        halwapuricheck.setSelected(false);
        channyfullcheck.setSelected(false);
        niharicheck.setSelected(false);
        halwaplatecheck.setSelected(false);
        
        //********************************
        fryeggqty.setEnabled(false);
        ommletteqty.setEnabled(false);
        parathaqty.setEnabled(false);
        naanqty.setEnabled(false);
        halwapuriqty.setEnabled(false);
        channyfullqty.setEnabled(false);
        channyhalfqty.setEnabled(false);
        halwaplateqty.setEnabled(false);
        
         //********************************
         
          fryeggqty.setText("0");
          ommletteqty.setText("0");
          parathaqty.setText("0");
          naanqty.setText("0");
          halwapuriqty.setText("0");
          channyfullqty.setText("0");
          channyhalfqty.setText("0");
          nihariqty.setText("0");
          halwaplateqty.setText("0");
          
        
        
        
    }//GEN-LAST:event_ResetActionPerformed

    private void parathacheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parathacheckActionPerformed
        // TODO add your handling code here:
        if (parathacheck.isSelected())
        {
            parathaqty.setEnabled(true);
            parathaqty.requestFocus();
            parathaqty.setText("");
        }
        
    }//GEN-LAST:event_parathacheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.JPanel breakfastMenu;
    private javax.swing.JCheckBox channyfullcheck;
    private javax.swing.JTextArea channyfullqty;
    private javax.swing.JCheckBox channyhalfcheck;
    private javax.swing.JTextArea channyhalfqty;
    private javax.swing.JCheckBox fryeggcheck;
    private javax.swing.JTextArea fryeggqty;
    private javax.swing.JCheckBox halwaplatecheck;
    private javax.swing.JTextArea halwaplateqty;
    private javax.swing.JCheckBox halwapuricheck;
    private javax.swing.JTextArea halwapuriqty;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JCheckBox naancheck;
    private javax.swing.JTextArea naanqty;
    private javax.swing.JCheckBox niharicheck;
    private javax.swing.JTextArea nihariqty;
    private javax.swing.JCheckBox ommlettecheck;
    private javax.swing.JTextArea ommletteqty;
    private javax.swing.JCheckBox parathacheck;
    private javax.swing.JTextArea parathaqty;
    // End of variables declaration//GEN-END:variables
}
