
import java.awt.event.KeyEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fahad
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Billing = new javax.swing.JPanel();
        jTextField10 = new javax.swing.JTextField();
        jScrollPane11 = new javax.swing.JScrollPane();
        teaqty = new javax.swing.JTextArea();
        teacheck = new javax.swing.JCheckBox();
        coffeecheck = new javax.swing.JCheckBox();
        jScrollPane8 = new javax.swing.JScrollPane();
        cofeeqty = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        lassiqty = new javax.swing.JTextArea();
        lassicheck = new javax.swing.JCheckBox();
        colacheck = new javax.swing.JCheckBox();
        jScrollPane10 = new javax.swing.JScrollPane();
        colaqty = new javax.swing.JTextArea();
        paymentSelection = new javax.swing.JComboBox<>();
        resetButton = new javax.swing.JButton();
        totalButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        moneyInput = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        total = new javax.swing.JTextArea();
        jTextField21 = new javax.swing.JTextField();
        jScrollPane17 = new javax.swing.JScrollPane();
        change = new javax.swing.JTextArea();
        jScrollPane18 = new javax.swing.JScrollPane();
        tax = new javax.swing.JTextArea();
        jScrollPane19 = new javax.swing.JScrollPane();
        subTotal = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        spriteqty = new javax.swing.JTextArea();
        spritecheck = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Billing.setBackground(new java.awt.Color(102, 8, 219));
        Billing.setToolTipText("");
        Billing.setPreferredSize(new java.awt.Dimension(400, 900));
        Billing.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(255, 255, 255));
        jTextField10.setFont(new java.awt.Font("Bahamas Bold", 0, 36)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("DRINKS");
        jTextField10.setBorder(null);
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        Billing.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 274, 52));

        jScrollPane11.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane11.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        teaqty.setColumns(20);
        teaqty.setRows(5);
        teaqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teaqtyKeyTyped(evt);
            }
        });
        jScrollPane11.setViewportView(teaqty);

        Billing.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 93, 31));

        teacheck.setBackground(new java.awt.Color(102, 8, 219));
        Billing.add(teacheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 52));

        coffeecheck.setBackground(new java.awt.Color(102, 8, 219));
        Billing.add(coffeecheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, 20));

        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        cofeeqty.setColumns(20);
        cofeeqty.setRows(5);
        cofeeqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cofeeqtyKeyTyped(evt);
            }
        });
        jScrollPane8.setViewportView(cofeeqty);

        Billing.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 93, 31));

        jScrollPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane9.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        lassiqty.setColumns(20);
        lassiqty.setRows(5);
        lassiqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lassiqtyKeyTyped(evt);
            }
        });
        jScrollPane9.setViewportView(lassiqty);

        Billing.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 93, 31));

        lassicheck.setBackground(new java.awt.Color(102, 8, 219));
        Billing.add(lassicheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, 20));

        colacheck.setBackground(new java.awt.Color(102, 8, 219));
        colacheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colacheckActionPerformed(evt);
            }
        });
        Billing.add(colacheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, 20));

        jScrollPane10.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane10.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        colaqty.setColumns(20);
        colaqty.setRows(5);
        colaqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                colaqtyKeyTyped(evt);
            }
        });
        jScrollPane10.setViewportView(colaqty);

        Billing.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 93, 31));

        paymentSelection.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        paymentSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Debit Card", "Master Card", "Coupon" }));
        paymentSelection.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        paymentSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentSelectionActionPerformed(evt);
            }
        });
        Billing.add(paymentSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 115, 34));

        resetButton.setBackground(new java.awt.Color(255, 255, 255));
        resetButton.setFont(new java.awt.Font("Clarendon BT", 0, 18)); // NOI18N
        resetButton.setText("RESET");
        resetButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        Billing.add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 630, 130, 44));

        totalButton.setBackground(new java.awt.Color(255, 255, 255));
        totalButton.setFont(new java.awt.Font("Clarendon BT", 0, 18)); // NOI18N
        totalButton.setText("TOTAL");
        totalButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        totalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalButtonActionPerformed(evt);
            }
        });
        Billing.add(totalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 115, 44));

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );

        Billing.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 10, 170));

        jScrollPane13.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane13.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        moneyInput.setEditable(false);
        moneyInput.setColumns(20);
        moneyInput.setRows(5);
        moneyInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                moneyInputKeyTyped(evt);
            }
        });
        jScrollPane13.setViewportView(moneyInput);

        Billing.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 115, 40));

        jScrollPane14.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane14.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        total.setEditable(false);
        total.setColumns(20);
        total.setRows(5);
        total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalKeyTyped(evt);
            }
        });
        jScrollPane14.setViewportView(total);

        Billing.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, 120, 30));

        jTextField21.setEditable(false);
        jTextField21.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jTextField21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField21.setText("TOTAL");
        Billing.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 400, 40));

        jScrollPane17.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane17.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        change.setEditable(false);
        change.setColumns(20);
        change.setRows(5);
        change.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                changeKeyTyped(evt);
            }
        });
        jScrollPane17.setViewportView(change);

        Billing.add(jScrollPane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 120, 30));

        jScrollPane18.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane18.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tax.setEditable(false);
        tax.setColumns(20);
        tax.setRows(5);
        tax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                taxKeyTyped(evt);
            }
        });
        jScrollPane18.setViewportView(tax);

        Billing.add(jScrollPane18, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 120, 30));

        jScrollPane19.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane19.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        subTotal.setEditable(false);
        subTotal.setColumns(20);
        subTotal.setRows(5);
        subTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                subTotalKeyTyped(evt);
            }
        });
        jScrollPane19.setViewportView(subTotal);

        Billing.add(jScrollPane19, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, 120, 30));

        jScrollPane12.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane12.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        spriteqty.setColumns(20);
        spriteqty.setRows(5);
        spriteqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                spriteqtyKeyTyped(evt);
            }
        });
        jScrollPane12.setViewportView(spriteqty);

        Billing.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 93, 31));

        spritecheck.setBackground(new java.awt.Color(102, 8, 219));
        spritecheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spritecheckActionPerformed(evt);
            }
        });
        Billing.add(spritecheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, 20));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SPRITE");
        Billing.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 110, 40));

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Total");
        Billing.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, 70, 40));

        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("COFFEE");
        Billing.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 110, 40));

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("LASSI");
        Billing.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 110, 40));

        jLabel20.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("COLA");
        Billing.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 110, 40));

        jLabel21.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("TEA");
        Billing.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 110, 40));

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Payment Method");
        Billing.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 150, 40));

        jLabel23.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Change");
        Billing.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 70, 40));

        jLabel24.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Tax");
        Billing.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 70, 40));

        jLabel25.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Sub Total");
        Billing.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 90, 40));

        getContentPane().add(Billing, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void teaqtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teaqtyKeyTyped

        char numberVal = evt.getKeyChar();
        if(!(Character.isDigit(numberVal))
            ||(numberVal ==KeyEvent.VK_BACK_SPACE)
            ||(numberVal ==KeyEvent.VK_DELETE))
        evt.consume();
        // TODO add your handling code here:
    }//GEN-LAST:event_teaqtyKeyTyped

    private void cofeeqtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cofeeqtyKeyTyped

        char numberVal = evt.getKeyChar();
        if(!(Character.isDigit(numberVal))
            ||(numberVal ==KeyEvent.VK_BACK_SPACE)
            ||(numberVal ==KeyEvent.VK_DELETE))
        evt.consume();
        // TODO add your handling code here:
    }//GEN-LAST:event_cofeeqtyKeyTyped

    private void lassiqtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lassiqtyKeyTyped

        char numberVal = evt.getKeyChar();
        if(!(Character.isDigit(numberVal))
            ||(numberVal ==KeyEvent.VK_BACK_SPACE)
            ||(numberVal ==KeyEvent.VK_DELETE))
        evt.consume();
        // TODO add your handling code here:
    }//GEN-LAST:event_lassiqtyKeyTyped

    private void colacheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colacheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colacheckActionPerformed

    private void colaqtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_colaqtyKeyTyped

        char numberVal = evt.getKeyChar();
        if(!(Character.isDigit(numberVal))
            ||(numberVal ==KeyEvent.VK_BACK_SPACE)
            ||(numberVal ==KeyEvent.VK_DELETE))
        evt.consume();
        // TODO add your handling code here:
    }//GEN-LAST:event_colaqtyKeyTyped

    private void paymentSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentSelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentSelectionActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed

        teaqty.setText(null);
        cofeeqty.setText(null);
        lassiqty.setText(null);
        colaqty.setText(null);
        spriteqty.setText(null);
        change.setText(null);
        tax.setText(null);
        subTotal.setText(null);
        total.setText(null);
        moneyInput.setText(null);

        //=====================

        teacheck.setSelected(false);
        coffeecheck.setSelected(false);
        lassicheck.setSelected(false);
        colacheck.setSelected(false);
        spritecheck.setSelected(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_resetButtonActionPerformed

    private void totalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalButtonActionPerformed

    private void moneyInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_moneyInputKeyTyped

        char numberVal = evt.getKeyChar();
        if(!(Character.isDigit(numberVal))
            ||(numberVal ==KeyEvent.VK_BACK_SPACE)
            ||(numberVal ==KeyEvent.VK_DELETE))
        evt.consume();
        // TODO add your handling code here:
    }//GEN-LAST:event_moneyInputKeyTyped

    private void totalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalKeyTyped

        char numberVal = evt.getKeyChar();
        if(!(Character.isDigit(numberVal))
            ||(numberVal ==KeyEvent.VK_BACK_SPACE)
            ||(numberVal ==KeyEvent.VK_DELETE))
        evt.consume();
        // TODO add your handling code here:
    }//GEN-LAST:event_totalKeyTyped

    private void changeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_changeKeyTyped

        char numberVal = evt.getKeyChar();
        if(!(Character.isDigit(numberVal))
            ||(numberVal ==KeyEvent.VK_BACK_SPACE)
            ||(numberVal ==KeyEvent.VK_DELETE))
        evt.consume();
        // TODO add your handling code here:
    }//GEN-LAST:event_changeKeyTyped

    private void taxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taxKeyTyped

        char numberVal = evt.getKeyChar();
        if(!(Character.isDigit(numberVal))
            ||(numberVal ==KeyEvent.VK_BACK_SPACE)
            ||(numberVal ==KeyEvent.VK_DELETE))
        evt.consume();
        // TODO add your handling code here:
    }//GEN-LAST:event_taxKeyTyped

    private void subTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subTotalKeyTyped

        char numberVal = evt.getKeyChar();
        if(!(Character.isDigit(numberVal))
            ||(numberVal ==KeyEvent.VK_BACK_SPACE)
            ||(numberVal ==KeyEvent.VK_DELETE))
        evt.consume();
        // TODO add your handling code here:
    }//GEN-LAST:event_subTotalKeyTyped

    private void spriteqtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spriteqtyKeyTyped

        char numberVal = evt.getKeyChar();
        if(!(Character.isDigit(numberVal))
            ||(numberVal ==KeyEvent.VK_BACK_SPACE)
            ||(numberVal ==KeyEvent.VK_DELETE))
        evt.consume();
        // TODO add your handling code here:
    }//GEN-LAST:event_spriteqtyKeyTyped

    private void spritecheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spritecheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spritecheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Billing;
    private javax.swing.JTextArea change;
    private javax.swing.JTextArea cofeeqty;
    private javax.swing.JCheckBox coffeecheck;
    private javax.swing.JCheckBox colacheck;
    private javax.swing.JTextArea colaqty;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JCheckBox lassicheck;
    private javax.swing.JTextArea lassiqty;
    private javax.swing.JTextArea moneyInput;
    private javax.swing.JComboBox<String> paymentSelection;
    private javax.swing.JButton resetButton;
    private javax.swing.JCheckBox spritecheck;
    private javax.swing.JTextArea spriteqty;
    private javax.swing.JTextArea subTotal;
    private javax.swing.JTextArea tax;
    private javax.swing.JCheckBox teacheck;
    private javax.swing.JTextArea teaqty;
    private javax.swing.JTextArea total;
    private javax.swing.JButton totalButton;
    // End of variables declaration//GEN-END:variables
}
